#!/bin/sh -l
source /usr/share/Modules/init/sh
module load intel19.5/magics/3.3.1
module load intel19.5/19.5.281
module load intel19.5/proj/6.2.1
module load intel19.5/udunits/2.2.26
module load intel19.5/szip/2.1.1
module load intel19.5/netcdf-threadsafe/C_4.7.2-F_4.5.2_CXX_4.3.1
module load intel19.5/hdf5-threadsafe/1.10.5
module load intel19.5/eccodes/2.12.5
module load intel19.5/cdo/1.9.8
